/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashinternal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ellan
 */
public class dashboardpage extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboardpage
     */
    public dashboardpage() {
        initComponents();
        
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy HH:mm:ss");
                String dateTime = formatter.format(now);
                jLabel1.setText(dateTime);
            }
        });
        t.start();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI)this.getUI();
        bif.setNorthPane(null);
    }
    
        Color enter  = new Color(136, 1, 17);
        Color exit = new Color(157,1,27);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dateandtime = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        description = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        seat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(157, 1, 27));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateandtime.setBackground(new java.awt.Color(157, 1, 27));
        dateandtime.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240)));
        dateandtime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateandtimeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dateandtimeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dateandtimeMouseExited(evt);
            }
        });
        dateandtime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Date and Time");
        dateandtime.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        jPanel1.add(dateandtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, 40));

        description.setBackground(new java.awt.Color(157, 1, 27));
        description.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240)));
        description.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                descriptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                descriptionMouseExited(evt);
            }
        });
        description.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Description");
        description.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        jPanel1.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 130, 40));

        seat.setBackground(new java.awt.Color(157, 1, 27));
        seat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240)));
        seat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seatMouseExited(evt);
            }
        });
        seat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pick Seat");
        seat.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        jPanel1.add(seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MM-dd-yyyy HH:mm:ss");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 190, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jDesktopPane1.setBackground(new java.awt.Color(0, 204, 0));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mafiaducksmoking-removebg-preview.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(85, 85, 85))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateandtimeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateandtimeMouseEntered
        dateandtime.setBackground(enter);
    }//GEN-LAST:event_dateandtimeMouseEntered

    private void dateandtimeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateandtimeMouseExited
        dateandtime.setBackground(exit);
    }//GEN-LAST:event_dateandtimeMouseExited

    private void dateandtimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateandtimeMouseClicked
     
    }//GEN-LAST:event_dateandtimeMouseClicked

    private void descriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionMouseClicked

    private void descriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionMouseEntered
        description.setBackground(enter);
    }//GEN-LAST:event_descriptionMouseEntered

    private void descriptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionMouseExited
        description.setBackground(exit);
    }//GEN-LAST:event_descriptionMouseExited

    private void seatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_seatMouseClicked

    private void seatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seatMouseEntered
        seat.setBackground(enter);
    }//GEN-LAST:event_seatMouseEntered

    private void seatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seatMouseExited
        seat.setBackground(exit);
    }//GEN-LAST:event_seatMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dateandtime;
    private javax.swing.JPanel description;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel seat;
    // End of variables declaration//GEN-END:variables
}
